export const imageConstants = {
  home: {
    headerIcon: require('../assets/images/headerIcon.png'),
    notification: require('../assets/images/homebell.png'),
    addressIcon: require('../assets/images/address.png'),
    back: require('../assets/images/back.png'),
    next: require('../assets/images/next.png'),
    tlogo: require('../assets/images/tlogo.png'),
    boldnext: require('../assets/images/boldnext.png'),
    calendar: require('../assets/images/calendar.png'),
    fabcalendar: require('../assets/images/fabcalendar.png'),
    eventLogo: require('../assets/images/eventLogo.png'),
    tick: require('../assets/images/tick.png'),
    cross: require('../assets/images/cross.png'),
    calendararrowleft: require('../assets/images/calendararrowleft.png'),
    calendararrowRight: require('../assets/images/calendararrowright.png'),
    highworth: require('../assets/images/hightworth.png'),
    cancel: require('../assets/images/cancel.png'),
    upload: require('../assets/images/upload.png'),
    downarrow: require('../assets/images/downarrow.png'),
    redheart: require('../assets/images/redheart.png'),
    circleRedTick: require('../assets/images/circleRedTick.png'),
    sendicon: require('../assets/images/sendicon.png'),
    editicon: require('../assets/images/editicon.png'),
    bin: require('../assets/images/bin.png'),
    cry: require('../assets/images/cry.png'),
    verifiedicon: require('../assets/images/verifiedicon.png'),
    p1: require('../assets/images/p1.png'),
    p2: require('../assets/images/p2.png'),
    p3: require('../assets/images/p3.png'),
    p1Active: require('../assets/images/Star.png'),
    p2Active: require('../assets/images/Wallet.png'),
    p3Active: require('../assets/images/Files.png'),
    dummyUserImage: require('../assets/images/place.jpg'),
    pen: require('../assets/images/pen.png'),
    vote: require('../assets/images/vote.png'),
    eye: require('../assets/images/eye.png'),
    invisible: require('../assets/images/invisible.png'),
    counterWhiteTick: require('../assets/images/counterWhiteTick.png'),
  },
  step2: {
    foodie: require('../assets/images/foodie.png'),
    creative: require('../assets/images/creative.png'),
    hardworking: require('../assets/images/hardworking.png'),
    smoking: require('../assets/images/smoking.png'),
    wine: require('../assets/images/wine.png'),
    analytical: require('../assets/images/analytical.png'),
    spontenous: require('../assets/images/spontenous.png'),
    introverted: require('../assets/images/introverted.png'),
    natureloving: require('../assets/images/natureloving.png'),
    travel: require('../assets/images/travel.png'),
    animallover: require('../assets/images/animallover.png'),
    adventures: require('../assets/images/adventures.png'),
  },
  welcomeToTolivi: {
    logo: require('../assets/images/welcomeToToliviLogo.png'),
  },
  signUp: {
    logo: require('../assets/images/tolivilogo.png'),
  },
  Step3: {
    camera: require('../assets/images/camera.png'),
    plus: require('../assets/images/plus.png'),
    remove: require('../assets/images/remove.png'),
  },
  WhoLikesYouPopUp: {
    heart: require('../assets/images/whiteheart.png'),
    mask: require('../assets/images/mask.png'),
  },
  myProfile: {
    edit: require('../assets/images/MyProfile/edit.png'),
    eye: require('../assets/images/MyProfile/eye.png'),
    home: require('../assets/images/MyProfile/home.png'),
    star: require('../assets/images/MyProfile/star.png'),
    heart: require('../assets/images/MyProfile/profileheart.png'),
    setting: require('../assets/images/MyProfile/setting.png'),
    back: require('../assets/images/back.png'),
  },
  MyTab: {
    profile: require('../assets/images/TabBar/profile.png'),
    chat: require('../assets/images/TabBar/chat.png'),
    event: require('../assets/images/TabBar/event.png'),
    home: require('../assets/images/TabBar/home.png'),
    activeHome: require('../assets/images/TabBar/homeActive.png'),
    activeEvent: require('../assets/images/TabBar/eventActive.png'),
    activeChat: require('../assets/images/TabBar/chatActive.png'),
    activeProfile: require('../assets/images/TabBar/profileActive.png'),
  },
  chat: {
    sendmsj: require('../assets/images/sendmsj.png'),
    chatcamera: require('../assets/images/chatcamera.png'),
    dot: require('../assets/images/3dot.png'),
    heart: require('../assets/images/cahtheart.png'),
    search: require('../assets/images/search.png'),
  },
  icons: {
    white_heart: require('../assets/icons/white_heart.png'),
    red_heart: require('../assets/icons/red_heart.png'),
    audio_file: require('../assets/icons/audio_file.png'),
  },
};
