export {default as ForgotPassword} from './forgotPassword'
export {default as Login} from './login'
export {default as ResetPassword} from './resetPassword'
export {default as SignUp} from './singup'
export {default as LoginWithEmail} from './loginWithEmail'
export {default as LoginWithNumber} from './loginWithNumber'
export {default as TermAndCondition} from './termsAndCondition'
