/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

export const textConstants = {
  appIntro: {
    skip: 'Skip',
    done: 'Done',
    back: 'Back',
  },
  textInputLabel: {
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    age: 'Age',
    selectRelation: 'Select Relation',
    dateOfBirth: 'Date of Birth',
  },
  btnText: {
    next: 'Next',
    signIn: 'Sign in',
    submit: 'Submit',
    done: 'Done',
    register: 'Register',
    uploadPrescription: 'Upload Prescription',
    restFilter: 'Reset Filter',
    applyFilter: 'Apply Filter',
    checkout: 'Checkout',
    addMoreTest: 'Add More Test',
    remove: 'Remove',
    requestNewCard: 'Request New Card',
    update: 'Update',
    sendRequest: 'Send Request',
    addMember: 'Add Member',
    cancel: 'Cancel',
    back: 'Back',
    accept: 'Accept',
    makePayment: 'Make Payment',
    proceedToBuy: 'Proceed to Buy',
    continueHomeScree: 'Continue to Home screen',
    bookNow: 'Book Now',
    applyPin_code: 'Apply Pincode',
    confirmLocation: 'Confirm Location',
    addLocation: 'Add Location',
    cancelBooking: 'Cancel Booking',
    reportPending: 'Report Pending',
    downloadReport: 'Download Report',
    addToCart: 'Add to Cart',
    continueToHome: 'Continue to Home screen',
  },
  login: {
    bySinging: 'By singing up, you agree with our',
    enter: 'Enter Your Mobile Number',
    weWillSend: 'We will send you an OTP to verify your details',
    loginText: 'Login',
    loginSubheading: 'Enter your login details to enter the application.',
    forgotPassword: 'Forgot Password ?',
    enterGuest: 'Enter as ',
    guest: 'Guest',
    donHaveAccount: `Don't have an Account?`,
    registerHere: 'Register here',
    or: 'OR',
    loginOtp: 'Login with OTP',
    loginGoogle: 'Login with Google',
    loginFacebook: 'Login with Facebook',
    readOur: 'Read our',
    termsCondition: 'Terms & Conditions',
    and: ' and ',
    privacyPolicy: 'Privacy Policy',
    accountRecovery: 'Account Recovery',
    accountRecoveryDesc: `Changed your phone number, \nor lost access to your facebook \n Account? We can help you login \n with your email.`,
    loginWithEmail: ' LOGIN WITH EMAIL',
    privicyButton: 'I AGREE',
    privicyTitle: 'Welcome to Partner.',
    privicyDesc: 'Please follow these House Rules.',
  },
  mobileNumber: {
    back: 'Back',
    mobileNUmber: 'Mobile Number',
    screenSubHeading: 'Enter your Mobile details to enter the application.',
  },
  signUp: {
    registration: 'Registration',
    screenSubHeading: 'Enter your details to Register with us',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    iAccept: 'I Accept',
  },
  otp: {
    enter: 'Enter the OTP sent to your mobile',
    // enter: 'Now Enter the OTP',
    weWillSend: 'We will send you an OTP to verify your details',

    resendOtp: 'Re-send OTP',
    resendCode: 'Resend code in',
  },
  resetPassword: {
    resetPassword: 'RESET PASSWORD',
    heading: 'Forgot your password?',
    subHeading1: 'Enter your email address to \n retrieve your password',
  },
  locationService: {
    locationService: 'Location Service',
    subHeading:
      'Turn on Location service in your Devices setting to get new offers and get Nearby Labs to get tested',
    allowWhileUsingApp: 'Allow while using App',
    allowTracking: 'Allow Tracking',
    dontAllow: `Dont't Allow`,
  },
  home: {
    setLocation: 'Set Location',
    browseLabTest: 'Browse Lab Test',
    uploadPrescription: 'Upload Prescription',
    findNearLabs: 'Find Nearby Labs',
    testPackage: 'Test Packages',
    seeAll: 'See All',
    bodyParts: 'Body Parts',
    condition: 'Conditions',
    blogs: 'Blogs',
    newsAndEvents: 'News and Events',
    trackBooking: 'Tarck Booking',
  },
  homeBottomBar: {
    home: 'Home',
    cart: 'Cart',
    search: 'Search',
    myAccount: 'My Account',
  },

  drawerMenu: {
    menu: 'Menu',
    bookings: 'Bookings',
    myFamilyMembers: 'My Family Members',
    membershipCards: 'Membership Cards',
    myAccount: 'My Account',
    myReports: 'My Reports',
    smartReports: 'Smart Reports',
    addresses: 'Addresses',
    blogs: 'Blogs',
    needHelp: 'Need Help ?',
    aboutDrBlal: 'About Dr. B Lal Lab',
    logout: 'Logout',
  },

  homeBottomMap: {
    trackBooking: 'Track Booking',
  },
  searchLabTestPackage: {
    heading: 'Search Lab Test/Package',
    enterNameTestBody: 'Enter Test Name, Body Part or Condition',
    filter: 'Filter',
    searchedResult: 'Search Result will be listed below',
    topTest: 'Top Test',
    topPackage: 'Top Packages',
  },
  needHelp: {
    needHelp: 'Need Help ?',
    viewAll: 'View All',
    covid19: 'COVID-19',
    requestHelp: 'Request Help',
  },
  findNearbyLabs: {
    findNearbyLabs: 'Find Nearby Labs',
    call: 'Call',
    direction: 'Direction',
  },
  applyFilter: {
    applyFilter: 'Apply Filter',
    state: 'State',
    area: 'Area',
    patientName: 'Patient Name',
    bookingStatus: 'Booking Status',
    date: 'Date',
  },
  myCart: {
    myCart: 'My Cart',
    addMoreTest: 'Add More Test',
    youCanAlsoAdd: 'You can also add',
  },
  myMembership: {
    myMembership: 'My Membership',
    requestUpgrade: 'Request Upgrade',
    patientNames: 'Patient Name',
    associatedMobile: 'Associated Mobile',
  },
  blogs: {
    blogs: 'Blogs',
    categories: 'Categories',
    popularBlog: `Popular Blog's`,
    latestBlog: `Latest Blog's`,
  },
  filter: {
    filter: 'Filter',
    categorySubCategory: 'Category/Sub Category',
  },
  myProfile: {
    myProfile: 'My Profile',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
  },
  myAccount: {
    myAccount: 'My Account',
    myProfile: 'My Profile',
    recommendationAndReminders: 'Recommendation & Reminders',
    inquiry: 'Inquiry',
  },
  myAddress: {
    myAddress: 'My Address',
    addNewAddress: 'Add New Address',
  },
  inquiry: {
    inQuiry: 'Inquiry',
    addNewAddress: 'Add new Address hat you wish to have',
    addAttachment: 'Add Attachment',
  },
  bookingSuccessful: {
    bookingSuccessful: 'Booking Successful',
    thanks:
      'Thanks you for submitting the Prescription. our team will get back to you soon.',
    booingId: 'Booking ID',
    uploadDateTime: 'Upload Date and Time',
  },
  requestHelp: {
    requestHelp: 'Request Help',
  },
  addFailyMember: {
    addFamilyMember: 'Add Family Member',
    enterpersonalDetail: 'Enter personal details for the member',
  },
  selectCard: {
    selectCard: 'Select Card',
    buyNow: 'Buy Now',
  },
  addCard: {
    addCard: 'Add Card',
    benefits: 'Benefits',
    enterPersonalDetail: 'Enter personal details for the member',
  },
  selectLocation: {
    selectLocation: 'Select Location',
    addNewAddres: 'Add new Address that you wish to have',
    useCurrentLocation: 'Use Current Location',
    usingGps: 'Using GPS',
  },
  map: {
    enterPincode: 'Enter Pincode',
  },
  selectAddress: {
    done: 'Done',
    enterPin_codeHere: 'Enter Pincode here',
    areaPincode: 'Area Pincode',
    selectAddress: 'Select Address',
    home: 'Home',
    office: 'Office',
    addNewAddress: 'Add New Address',
  },
  setLocation: {
    setLocation: 'Set Location',
    change: 'Change',
  },
  addNewAddress: {
    addNewAddress: 'Add New Address',
    subHeading: 'Add new Address that you wish to have',
    addressType: 'Address Type',
    home: 'Home',
    office: 'Office',
    other: 'Other',
  },
  bloodTest: {
    bloodTest: 'Blood test',
    recommendedFor: 'Recommended for',
    ageGroup: 'Age Group',
    sampleType: 'Sample Type',
    reportGenerationTime: 'Report generation Time',
    sampleTest: 'Sample Test',
    specialPreparation: 'Special Preparation/Instructions',
    collectionType: 'Collection type',
    twoOption: '(2 options)',
    home: 'Home',
    lab: 'Lab',
  },
  fullBodyCheckup: {
    fullBodyCheckup: 'Full Body Checkup',
    totalTest: 'Total Tests',
  },
  myBooking: {
    myBooking: 'My Booking',
    trackPro: 'Track PRO',
    viewMore: 'View More',
    rateNow: 'Rate Now',
    bookingConfirmed: 'Booking Confirmed',
    invoicePdf: 'Invoice.pdf',
    paymentDetails: 'Payment Details',
    paid: 'Paid(Online)',
    testPrice: 'Test Price',
    couponDiscount: 'Coupon Discount',
    totalAmount: 'Total (Amount)',
    totalPayable: 'Total (Payable)',
    pickupAddress: 'Pickup Address',
    waitingPro_assiging: 'Waiting for the Pro assigning',
    call: 'Call',
    ratingAndReview: 'Rating and Review',
    proRating: 'PRO Rating',
    testRating: 'Test Rating',
    labCollection: 'Lab Collection',
    collectionType: 'Collection Type',
    labDetail: 'Lab Detail',
  },
  reports: {
    reports: 'Reports',
    subHeading: 'Select the patient for whom you want to see the report',
    gender: 'Gender',
    homePickup: 'Home Pickup',
    labNumber: 'Lab Number',
    collectionDone: 'Collection Done',
  },
  selectPatient: {
    addNewMember: 'Add New Member',
  },
  addFamilyMember: {
    addFamilyMember: 'Add Family Member',
  },
  bookingDetailScreen: {
    bookingDetail: 'Booking Details',
    provideDetailBooking: 'Provide Detail for booking',
    selectType: 'Select Type',
    required: '(Required)',
    selectTime: 'Select Time',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    special_instructions: 'Special Instruction',
  },
  payment: {
    payment: 'Payment',
    selectPaymentMode: 'Select Payment Mode',
    online: 'Online',
    paymentCanBe_Online: 'Payment can be done Online',
    paymentCanBe_lab: 'Payment can be done at Lab',
    pay_To_lab: 'Pay to Lab',
    viewOffer: 'View Offer',
    couponCode: 'Coupon Code',
  },
  bookingAlert: {
    ThanksYou:
      'Thank you for blessing with us. PRO agent will be assigned to you shortly for pickup',
  },
  notification: {
    notifications: 'Notifications',
  },
  validationMessages: {
    gender_required: 'Please select gender',
    email_required: 'Email field is required.',
    email_not_valid: 'Email field is not containing vaild email.',
    password_required: 'Password field is required.',
    lastName: 'Password field is required.',
    oldPassword_required: 'Old password field is required.',
    password_not_in_alphaNumeric:
      'Password should contain lower & uppercase, a number, and a special character with minimum 6 character.',
    name_required: 'Name field is required.',
    firstName: 'First Name field is required.',
    last_Name: 'Last Name field is required.',
    referal_Code: 'Refral Code field is required.',
    name_not_in_length:
      'Name must be minimum 4 character & maximum 20 character long.',
    phone_number_required: 'Mobile number field is required.',
    phone_number_email_required: 'Mobile number /Email field is required.',
    phone_number_not_vaild: 'This mobile number is not valid.',
    amountNotValid: 'This amount is not valid.',
    otp_required: 'OTP field is required.',
    valid_otp: 'OTP  must be minimum 4 digits.',
    last_name_required: 'Last name field is required.',
    last_name_not_in_length:
      'Last name must be minimum 4 character & maximum 20 character long.',
    couponCode_required: 'Coupon code is required',
    nameOfAddress_required: 'Name of address required',
    landmark_required: 'Landmark required',
    areaName_required: 'Area name required',
    Imei_required: 'IMEI number required',
    iban_required: 'iban required',
    accountNo_required: ' Account number required',
    accountNoNotValid: ' Account number is not valid',
    swiftCode_required: 'Swift code required',
    bankName_required: 'Bank name required',
    accountHolderName_required: 'Account holder name Required',
    ifscCode_required: 'IFSC code Required',
    ifcdCode_not_valid: 'IFSC code not not valid',
    bank_Name_required: 'Bank Name field is required.',
    bankName_not_valid:
      'Bank Name must be character and minimum 4 character & maximum 20 character long.',
    subjectRequired: ' Subject field  required',
    messageRequired: 'Message field  required',
    walletAmount: 'Amount field  required',
    fullName: 'Full Name field  required',
    fullNameNotValid: 'Full Name is not valid',
    country: 'Country Name field  required',
    countryNotValid: 'Country Name is not  valid',
    sex: 'This field is required',
    city: 'City field is required',
    subjectValidation: 'Subject is not valid',
    ReferalCode: 'Referral Code is Required',
    ReferalCodeValidation: 'Referral Code is not valid',
    category: 'This field is required',
    accountType: 'This field is required',
    subCategory: 'This field is required',
    language: 'This field is required',
    educationalQualification: 'This field is required',
    areaOfTraining: 'This field is required',
    accountHolderNameNotValid: 'Account Holder Name is not valid',
    cancelMessage: 'Cancellation reason is required',
  },

  formPlaceHolder: {
    emailAddress: 'Email Address',
    password: 'Password',
    oldPassword: 'Confirm Password',
    newPassword: 'New Password',
    firstName: 'First name',
    lastName: 'Last name',
    gender: 'Gender',
    confirmPassword: 'Confirm Password',
    varificationcode: 'Enter Verification Code',
    phonenumber: 'Mobile number ',
    referalCode: ' Referral code',
    selectcity: 'Select your city',
    phone_email: 'Mobile number/Email ',
  },
};
